export const MOVIES_GENRES_REQUEST = 'MOVIES_GENRES_REQUEST';
export const MOVIES_GENRES_SUCCESS = 'MOVIES_GENRES_SUCCESS';
export const MOVIES_GENRES_ERROR = 'MOVIES_GENRES_ERROR';
export const MOVIES_GENRES_RESET = 'MOVIES_GENRES_RESET';

export const MOVIES_BY_GENRES_REQUEST = 'MOVIES_BY_GENRES_REQUEST';
export const MOVIES_BY_GENRES_SUCCESS = 'MOVIES_BY_GENRES_SUCCESS';
export const MOVIES_BY_GENRES_ERROR = 'MOVIES_BY_GENRES_ERROR';
export const MOVIES_BY_GENRES_RESET = 'MOVIES_BY_GENRES_RESET';