export const MOVIES_TOP_RATED_REQUEST = 'MOVIES_TOP_RATED_REQUEST';
export const MOVIES_TOP_RATED_SUCCESS = 'MOVIES_TOP_RATED_SUCCESS';
export const MOVIES_TOP_RATED_ERROR = 'MOVIES_TOP_RATED_ERROR';
export const MOVIES_TOP_RATED_RESET = 'MOVIES_TOP_RATED_RESET';

export const MOVIES_POPULAR_REQUEST = 'MOVIES_POPULAR_REQUEST';
export const MOVIES_POPULAR_SUCCESS = 'MOVIES_POPULAR_SUCCESS';
export const MOVIES_POPULAR_ERROR = 'MOVIES_POPULAR_ERROR';
export const MOVIES_POPULAR_RESET = 'MOVIES_POPULAR_RESET';

export const MOVIES_UPCOMING_REQUEST = 'MOVIES_UPCOMING_REQUEST';
export const MOVIES_UPCOMING_SUCCESS = 'MOVIES_UPCOMING_SUCCESS';
export const MOVIES_UPCOMING_ERROR = 'MOVIES_UPCOMING_ERROR';
export const MOVIES_UPCOMING_RESET = 'MOVIES_UPCOMING_RESET';

export const MOVIES_BANNER_REQUEST = 'MOVIES_BANNER_REQUEST';
export const MOVIES_BANNER_SUCCESS = 'MOVIES_BANNER_SUCCESS';
export const MOVIES_BANNER_ERROR = 'MOVIES_BANNER_ERROR';
export const MOVIES_BANNER_RESET = 'MOVIES_BANNER_RESET';

export const MOVIES_LIST_REQUEST = 'MOVIES_LIST_REQUEST';
export const MOVIES_LIST_SUCCESS = 'MOVIES_LIST_SUCCESS';
export const MOVIES_LIST_ERROR = 'MOVIES_LIST_ERROR';
export const MOVIES_LIST_RESET = 'MOVIES_LIST_RESET';

export const MOVIES_SINGLE_REQUEST = 'MOVIES_SINGLE_REQUEST';
export const MOVIES_SINGLE_SUCCESS = 'MOVIES_SINGLE_SUCCESS';
export const MOVIES_SINGLE_ERROR = 'MOVIES_SINGLE_ERROR';
export const MOVIES_SINGLE_RESET = 'MOVIES_SINGLE_RESET';
