export const USER_SIGN_IN_REQUEST = 'USER_SIGN_IN_REQUEST';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_ERROR = 'USER_SIGN_IN_ERROR';

export const USER_SIGN_OUT = 'USER_SIGN_OUT';

export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_ERROR = 'USER_SIGN_UP_ERROR';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR';

export const USER_ADD_MOVIE_REQUEST = 'USER_ADD_MOVIE_REQUEST';
export const USER_ADD_MOVIE_SUCCESS = 'USER_ADD_MOVIE_SUCCESS';
export const USER_ADD_MOVIE_ERROR = 'USER_ADD_MOVIE_ERROR';

export const USER_DELETE_MOVIE_REQUEST = 'USER_DELETE_MOVIE_REQUEST';
export const USER_DELETE_MOVIE_SUCCESS = 'USER_DELETE_MOVIE_SUCCESS';
export const USER_DELETE_MOVIE_ERROR = 'USER_DELETE_MOVIE_ERROR';

export const USER_GET_MOVIE_LIST_REQUEST = 'USER_GET_MOVIE_LIST_REQUEST';
export const USER_GET_MOVIE_LIST_SUCCESS = 'USER_GET_MOVIE_LIST_SUCCESS';
export const USER_GET_MOVIE_LIST_ERROR = 'USER_GET_MOVIE_LIST_ERROR';